my_project/apps/core/urls.py
from django.urls import re_path

from .views import (
    ping,
    WelcomeView,
    ViteExample,
)

app_name = 'core'
urlpatterns = [
    re_path(r'^ping/?$', ping, name="ping"),
    re_path(r'^/?$', WelcomeView.as_view(), name="welcome"),
    re_path(r'^vite/?$', ViteExample.as_view(), name="vite_example"),
]

my_project/apps/core/views.py
from django.http import HttpResponse
from django.views.generic import TemplateView


def ping(request):
    """
    Health check url, it should return simplest and fastest response possible.

    It is used for checking availability
    """
    return HttpResponse("ok")


class WelcomeView(TemplateView):
    """
    Starter view
    """

    template_name = "core/welcome.html"


class ViteExample(TemplateView):
    """
    Vite example app here
    """

    template_name = "core/vite_example.html"

    @property
    def test_data(self) -> dict:
        """
        Add dummy data to the demplate
        """
        return {
            "yes": True,
            "no": False,
            "none": None,
            "text": "Lorem ipsum dolor sit amet",
            "list": [
                123,
                True,
                False,
                None,
                {"key": "value"},
            ],
            "dict": {
                "foo": "bar",
                "eggs": "spam",
            },
        }

my_project/apps/core/templates/core/vite_example.html
{% extends "base.html" %}
{% load django_vite %}

{% block extra-head %}
  {{ view.test_data|json_script:"test" }}
  {% vite_hmr_client %}
  {% vite_asset 'js/test.js' %}
  {% vite_asset 'js/main.js' %}
{% endblock extra-head %}

{% block content %}
  <h1>This is plain vue app</h1>
  <section>
    <div id="app1"></div>
  </section>
  <h1>This is vuetify app</h1>
  <section>
    <div id="app"></div>
  </section>
  <hr>
{% endblock content %}

my_project/apps/core/templates/core/welcome.html
{% extends "base.html" %}

{% block content %}
  <div class="dn-min-side">
    <div class="body">
      <div class="wrapper">
        <div class="grid">
          <h3>Hi there!</h3>
          <p>Lets get started</p>
          <p><a href="{% url 'core:vite_example' %}">See Vite example app here</a></p>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

my_project/templates/base.html
{% load i18n static %}
<!DOCTYPE html>
<html>
  <head>
    {% if view.prevent_search_indexing %}
      <meta name="robots" content="noindex, nofollow">
    {% endif %}

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1; user-scalable=0;">
    <title>{{ view.title|default:"My project" }}</title>
    <link href="{% static "material_design_icons/css/materialdesignicons.min.css" %}" rel="stylesheet">

    {% include "include/global_variables.html" %}

    {% block css_block %}
      {# Global CSS files #}
    {% endblock css_block %}
    {% block extra-head %}{% endblock extra-head %}
  </head>

  <body class="{% if view.body_class %} {{ view.body_class }}{% elif view_body_class %} {{ view_body_class }}{% endif %}">
    {% block content %}{% endblock %}
    {% block js_block %}
      {# Global JS files #}
    {% endblock %}
    {% block body_end %} {% endblock %}
  </body>
</html>

my_project/templates/include/global_variables.html
{{ global_variables|json_script:"__globalVariables__" }}
<script type="text/javascript">
  window.__app__ = JSON.parse(document.getElementById('__globalVariables__').textContent);
</script>